### ISSUE TITLE
Export encountered errors on following paths: /chat/page: /chat

### ISSUE THREAD

**Issue by giuliohome** [microsoft/azurechat#190]
I encountered some errors while [merging the latest commits](https://github.com/giuliohome-org/azurechat/commit/f57878b3e014b4cf8db17dc0d0af31f66025dcd5) into my fork. Specifically, these errors seem to be related to the paths /chat/page and /chat.

I'm currently investigating to determine if there's anything I might have overlooked or done incorrectly on my end. Any insights or assistance with this issue would be greatly appreciated.

Below the detailed log

```
   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types ...
   Collecting page data ...
   Generating static pages (0/9) ...

   Generating static pages (2/9) 

   Generating static pages (4/9) 
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:637:13)
    at new t.Pi (/home/runner/work/azurechat/azurechat/src/.next/server/chunks/312.js:6:73343)
    at new i (/home/runner/work/azurechat/azurechat/src/.next/server/chunks/804.js:1:417)
    at i.getInstance (/home/runner/work/azurechat/azurechat/src/.next/server/chunks/804.js:1:691)
    at h (/home/runner/work/azurechat/azurechat/src/.next/server/chunks/402.js:1:5669)
    at m (/home/runner/work/azurechat/azurechat/src/.next/server/app/chat/page.js:1:4993)
    at /home/runner/work/azurechat/azurechat/src/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:135:75145
    at /home/runner/work/azurechat/azurechat/src/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:135:75274
    at async eg (/home/runner/work/azurechat/azurechat/src/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:135:74968) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}

Error occurred prerendering page "/chat". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:637:13)
    at new t.Pi (/home/runner/work/azurechat/azurechat/src/.next/server/chunks/312.js:6:73343)
    at new i (/home/runner/work/azurechat/azurechat/src/.next/server/chunks/804.js:1:417)
    at i.getInstance (/home/runner/work/azurechat/azurechat/src/.next/server/chunks/804.js:1:691)
    at h (/home/runner/work/azurechat/azurechat/src/.next/server/chunks/402.js:1:5669)
    at m (/home/runner/work/azurechat/azurechat/src/.next/server/app/chat/page.js:1:4993)
    at /home/runner/work/azurechat/azurechat/src/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:135:75145
    at /home/runner/work/azurechat/azurechat/src/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:135:75274
    at async eg (/home/runner/work/azurechat/azurechat/src/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:135:74968)

   Generating static pages (6/9) 

 ✓ Generating static pages (9/9) 

> Export encountered errors on following paths:
	/chat/page: /chat
Error: Process completed with exit code 1.
```

**Comment by giuliohome** [comment]
Possibly related to my [PR](https://github.com/microsoft/azurechat/pull/185).

Tracking there and closing this issue here.
