### ISSUE TITLE
Error when launching the app

### ISSUE THREAD

**Issue by nselvase** [microsoft/azurechat#208]
Steps to replicate:

1) cloned the repo locally.
2) Updated the environment variable. 
3) `npm install` (under src folder).
4) `npm run dev` gives the following error - **Internal error: TypeError [ERR_INVALID_STATE]: Invalid state: ReadableStream is already closed**
5) `npm audit fix `resolves few vulnerabilities but comes up with different error - **⨯ Internal error: Error: The render was aborted by the server without a reason.**
6) The app is able to run in localhost but just the general chat. When trying to upload the file,  error pops up - "Azure search environment variables are not configured".

**Comment by thivy** [comment]
@nselvase 

Similar to this issue #204 

Could you please make sure you have the latest version of the code and also make sure that the Document intelligence endpoints are configured correctly?

If you are still facing this error are you able to provide the logs from your VSCode console?

**Comment by schneutzi-81** [comment]
running is the same error. I checked the endpoint and cant find any mistake. 

Here is my output from the terminal 

> azure-open-ai-accelerator@0.1.0 dev
> next dev

  ▲ Next.js 13.5.3
  - Local:        http://localhost:3000
  - Environments: .env.local
  - Experiments (use at your own risk):
     · serverActions
     · serverActionsBodySizeLimit

 ✓ Ready in 4.3s
 ○ Compiling /page ...
 ✓ Compiled /page in 3.5s (883 modules)
 ✓ Compiled in 790ms (307 modules)
 ✓ Compiled /api/auth/[...nextauth]/route in 769ms (737 modules)
 ○ Compiling /chat/page ...
 ✓ Compiled /chat/page in 3.4s (1299 modules)
 ⨯ Internal error: TypeError [ERR_INVALID_STATE]: Invalid state: ReadableStream is already closed
    at new NodeError (node:internal/errors:405:5)
    at ReadableByteStreamController.enqueue (node:internal/webstreams/readablestream:1154:13)
    at eX (C:\Users\schne\OneDrive\Dokumente\code\azurechat-main\azurechat-main\src\node_modules\next\dist\compiled\next-server\app-page-experimental.runtime.dev.js:22:94440)
    at eK (C:\Users\schne\OneDrive\Dokumente\code\azurechat-main\azurechat-main\src\node_modules\next\dist\compiled\next-server\app-page-experimental.runtime.dev.js:22:93738)
    at Timeout._onTimeout (C:\Users\schne\OneDrive\Dokumente\code\azurechat-main\azurechat-main\src\node_modules\next\dist\compiled\next-server\app-page-experimental.runtime.dev.js:22:90381)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
 ⚠ ./node_modules/ws/lib/buffer-util.js
Module not found: Can't resolve 'bufferutil' in 'C:\Users\schne\OneDrive\Dokumente\code\azurechat-main\azurechat-main\src\node_modules\ws\lib'

Import trace for requested module:
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/websocket.js
./node_modules/ws/index.js
./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/WebsocketMessageAdapter.js
./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/Exports.js
./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/microsoft.cognitiveservices.speech.sdk.js
./features/chat/chat-ui/chat-speech/use-speech-to-text.ts
./features/chat/chat-ui/chat-context.tsx

./node_modules/ws/lib/validation.js
Module not found: Can't resolve 'utf-8-validate' in 'C:\Users\schne\OneDrive\Dokumente\code\azurechat-main\azurechat-main\src\node_modules\ws\lib'

Import trace for requested module:
./node_modules/ws/lib/validation.js
./node_modules/ws/lib/receiver.js
./node_modules/ws/index.js
./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/WebsocketMessageAdapter.js
./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/Exports.js
./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/microsoft.cognitiveservices.speech.sdk.js
./features/chat/chat-ui/chat-speech/use-speech-to-text.ts
./features/chat/chat-ui/chat-context.tsx
 ○ Compiling /chat/[id]/page ...
(node:22896) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
